# Generated by Django 3.2.5 on 2021-10-07 04:22

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mauser', models.CharField(max_length=255)),
                ('dienthoai', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to='user/%Y/%m')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KhongGian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makg', models.CharField(max_length=255, unique=True)),
                ('tenkg', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maloaihang', models.CharField(max_length=255)),
                ('tenloaihang', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MauSac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masp', models.CharField(max_length=255)),
                ('tensp', models.CharField(max_length=255, unique=True)),
                ('mota', ckeditor.fields.RichTextField()),
                ('baohanh', models.CharField(max_length=255)),
                ('dongianiemyet', models.CharField(max_length=255)),
                ('giakhuyenmai', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('shipping', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('hinhsp', models.ImageField(upload_to='sanpham/%Y/%m')),
                ('khonggian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.khonggian')),
                ('loaihang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanpham', to='shopapp.loaihang')),
                ('mausac', models.ManyToManyField(blank=True, null=True, related_name='sanpham', to='shopapp.MauSac')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('matag', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPhamView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('sanpham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sanpham')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='sanpham', to='shopapp.Tag'),
        ),
        migrations.CreateModel(
            name='Nhanxet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('noidung', models.TextField()),
                ('nguoinhanxet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mancc', models.CharField(max_length=255)),
                ('tenncc', models.CharField(max_length=255, unique=True)),
                ('dienthoai', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('hinhncc', models.ImageField(upload_to='nhacungcap/%Y/%m')),
                ('active', models.BooleanField(default=True)),
                ('loaihang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.loaihang')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madonhang', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('soluongban', models.CharField(max_length=255)),
                ('dongiaban', models.CharField(max_length=255)),
                ('khuyenmai', models.CharField(max_length=255)),
                ('makhachhang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('masp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='Danhgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('danhgia', models.PositiveSmallIntegerField(default=0)),
                ('nguoitao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sanpham')),
            ],
            options={
                'abstract': False,
                'unique_together': {('sanpham', 'nguoitao')},
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'like'), (1, 'haha'), (2, 'heart')], default=0)),
                ('nguoitao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sanpham')),
            ],
            options={
                'abstract': False,
                'unique_together': {('sanpham', 'nguoitao')},
            },
        ),
    ]
