# Generated by Django 3.2.5 on 2021-10-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20211007_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='matag',
        ),
    ]
