# Generated by Django 3.2.5 on 2021-10-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_tag_matag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
