# Generated by Django 3.2.5 on 2021-10-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_sanpham_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='hinhsp',
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='mota',
            field=models.TextField(max_length=255),
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diachi', models.ImageField(upload_to='sanpham/%Y/%m')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.sanpham')),
            ],
        ),
    ]
