# Generated by Django 3.2.5 on 2021-10-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_auto_20211014_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinhanhsanpham',
            name='sanpham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diachi', to='shopapp.sanpham'),
        ),
    ]
