# Generated by Django 3.2.5 on 2021-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_hinhanhsanpham_sanpham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='masp',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='soluongban',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='donhang',
            field=models.ManyToManyField(blank=True, null=True, related_name='sanpham', to='shopapp.DonHang'),
        ),
    ]
