# Generated by Django 3.2.5 on 2021-10-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_auto_20211026_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='donhang',
        ),
    ]
