# Generated by Django 3.2.5 on 2021-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_remove_sanpham_donhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hinhanh',
            field=models.ImageField(default=None, upload_to='sanpham/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='stock',
            field=models.CharField(max_length=255),
        ),
    ]
